name: CI

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  start-container-and-checkout:
    runs-on: ubuntu-latest
    container:
      image: busybox
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
